import React from 'react';



export const areYouReady = (props) => {
  return (
    <div>
        <div id="doc" className="markdown-body container-fluid" style={{position: 'relative'}}><p><img src="https://i.imgur.com/1QgrNNw.png" alt="Ironhack Logo" /></p><h1 id="Are-you-Ready"><a className="anchor hidden-xs" href="#Are-you-Ready" title="Are-you-Ready"><span className="octicon octicon-link" /></a>Are you Ready?</h1><h2 id="Test-Explication"><a className="anchor hidden-xs" href="#Test-Explication" title="Test-Explication"><span className="octicon octicon-link" /></a>Test Explication</h2><p>You will need to complete this test, from Iteration 1 to Iteration 4 , to achieve a technical interview. Once you have completed all 4 iterations, send your final completed code to <a href="mailto:ta-web-mad@ironhack.com" target="_blank">ta-web-mad@ironhack.com</a>.</p><h2 id="Iteration-1"><a className="anchor hidden-xs" href="#Iteration-1" title="Iteration-1"><span className="octicon octicon-link" /></a>Iteration 1</h2><p>First you will need to print in the console a list of numbers that starts in 1 and ends in 100.</p><p className="highlight"><img src="https://media.giphy.com/media/9u18ZDpwxobaLIouFL/giphy.gif" alt /></p><h4 id="Start-coding-here"><a className="anchor hidden-xs" href="#Start-coding-here" title="Start-coding-here"><span className="octicon octicon-link" /></a>Start coding here!</h4><iframe height={450} src="https://repl.it/@ta_web_mad/areyoureadyIteration1?language=javascript&lite=true" allowFullScreen="true" style={{width: '100%'}}>
          </iframe><h2 id="Iteration-2"><a className="anchor hidden-xs" href="#Iteration-2" title="Iteration-2"><span className="octicon octicon-link" /></a>Iteration 2</h2><p>Keeping the code of the first iteration you need to add a condition that you need to replace all the numbers that are divisible by 3 with the word ‘Iron’.</p><p><img src="https://media.giphy.com/media/BM0SbmoegSbN31KOsy/giphy.gif" alt /></p><h4 id="Start-coding-here"><a className="anchor hidden-xs" href="#Start-coding-here" title="Start-coding-here"><span className="octicon octicon-link" /></a>Start coding here!</h4><iframe height={450} src="https://repl.it/@ta_web_mad/areyoureadyIteration2?language=javascript&lite=true" allowFullScreen="true" style={{width: '100%'}}>
          </iframe><h2 id="Iteration-3"><a className="anchor hidden-xs" href="#Iteration-3" title="Iteration-3"><span className="octicon octicon-link" /></a>Iteration 3</h2><p>Keeping the code of the second iteration you need to add another condition that you need to replace all the numbers that are divisible by 5 with the word ‘Hack’.</p><p><img src="https://media.giphy.com/media/wKzEgZYhDcGAhLbG5e/giphy.gif" alt /></p><h4 id="Start-coding-here"><a className="anchor hidden-xs" href="#Start-coding-here" title="Start-coding-here"><span className="octicon octicon-link" /></a>Start coding here!</h4><iframe height={450} src="https://repl.it/@ta_web_mad/areyoureadyIteration3?language=javascript&lite=true" allowFullScreen="true" style={{width: '100%'}}>
          </iframe><h2 id="Iteration-4"><a className="anchor hidden-xs" href="#Iteration-4" title="Iteration-4"><span className="octicon octicon-link" /></a>Iteration 4</h2><p>Keeping the code of the third iteration you need to add another condition that you need to replace all the numbers that are divisible by 3 and 5 with the word ‘IronHack’.</p><p><img src="https://media.giphy.com/media/1X5fOHjXJA2tZICooY/giphy.gif" alt /></p><h4 id="Start-coding-here"><a className="anchor hidden-xs" href="#Start-coding-here" title="Start-coding-here"><span className="octicon octicon-link" /></a>Start coding here!</h4><iframe height={450} src="https://repl.it/@ta_web_mad/areyoureadyIteration4?language=javascript&lite=true" allowFullScreen="true" style={{width: '100%'}}>
          </iframe></div>
        <div className="ui-toc dropup unselectable hidden-print" style={{display: 'none'}}>
          <div className="pull-right dropdown">
            <a id="tocLabel" className="ui-toc-label btn btn-default" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" title="Table of content">
              <i className="fa fa-bars" />
            </a>
            <ul id="ui-toc" className="ui-toc-dropdown dropdown-menu" aria-labelledby="tocLabel">
              <div className="toc"><ul className="nav"><li className><a href="#Are-you-Ready" title="Are you Ready?">Are you Ready?</a><ul className="nav"><li><a href="#Test-Explication" title="Test Explication">Test Explication</a></li><li><a href="#Iteration-1" title="Iteration 1">Iteration 1</a><ul className="nav"><li><a href="#Start-coding-here" title="Start coding here!">Start coding here!</a></li></ul></li><li><a href="#Iteration-2" title="Iteration 2">Iteration 2</a><ul className="nav"><li><a href="#Start-coding-here" title="Start coding here!">Start coding here!</a></li></ul></li><li><a href="#Iteration-3" title="Iteration 3">Iteration 3</a><ul className="nav"><li><a href="#Start-coding-here" title="Start coding here!">Start coding here!</a></li></ul></li><li><a href="#Iteration-4" title="Iteration 4">Iteration 4</a><ul className="nav"><li><a href="#Start-coding-here" title="Start coding here!">Start coding here!</a></li></ul></li></ul></li></ul></div><div className="toc-menu"><a className="expand-toggle" href="#">Expand all</a><a className="back-to-top" href="#">Back to top</a><a className="go-to-bottom" href="#">Go to bottom</a></div>
            </ul>
          </div>
        </div>
        <div id="ui-toc-affix" className="ui-affix-toc ui-toc-dropdown unselectable hidden-print" data-spy="affix" style={{top: 17, display: 'none'}}>
          <div className="toc"><ul className="nav"><li className><a href="#Are-you-Ready" title="Are you Ready?">Are you Ready?</a><ul className="nav"><li><a href="#Test-Explication" title="Test Explication">Test Explication</a></li><li><a href="#Iteration-1" title="Iteration 1">Iteration 1</a><ul className="nav"><li><a href="#Start-coding-here" title="Start coding here!">Start coding here!</a></li></ul></li><li><a href="#Iteration-2" title="Iteration 2">Iteration 2</a><ul className="nav"><li><a href="#Start-coding-here" title="Start coding here!">Start coding here!</a></li></ul></li><li><a href="#Iteration-3" title="Iteration 3">Iteration 3</a><ul className="nav"><li><a href="#Start-coding-here" title="Start coding here!">Start coding here!</a></li></ul></li><li><a href="#Iteration-4" title="Iteration 4">Iteration 4</a><ul className="nav"><li><a href="#Start-coding-here" title="Start coding here!">Start coding here!</a></li></ul></li></ul></li></ul></div><div className="toc-menu"><a className="expand-toggle" href="#">Expand all</a><a className="back-to-top" href="#">Back to top</a><a className="go-to-bottom" href="#">Go to bottom</a></div>
        </div>
      </div>
  );
  };