import React from 'react'

export const Strings = () => {
  return (
    <div>
        <div id="doc" className="markdown-body container-fluid" style={{position: 'relative'}}><p><img src="https://i.imgur.com/1QgrNNw.png" alt="Ironhack Logo" /></p><h1 id="Basic-Data-Types-Strings"><a className="anchor hidden-xs" href="#Basic-Data-Types-Strings" title="Basic-Data-Types-Strings"><span className="octicon octicon-link" /></a>Basic Data Types: Strings</h1><h2 id="Learning-Goals"><a className="anchor hidden-xs" href="#Learning-Goals" title="Learning-Goals"><span className="octicon octicon-link" /></a>Learning Goals</h2><p>After this lesson, you will be able to:</p><ul>
            <li>Explain what a string is in JavaScript.</li>
            <li>Create a string.</li>
            <li>Use some extra string tips &amp; tricks.</li>
          </ul><h2 id="What-is-a-string"><a className="anchor hidden-xs" href="#What-is-a-string" title="What-is-a-string"><span className="octicon octicon-link" /></a>What is a string?</h2><p>A <code>String</code> in any programming language is simply <strong>a sequence of characters</strong> between quotes. A <code>character</code> can be a letter, number, punctuation, or even things such as new lines and tabs. It just needs to be between quotes.</p><p>Strings are some of the most common data types in any programming language. You will use them to represent things like names, countries, foods, and any sequence of characters you can think of!</p><h2 id="Creating-a-String"><a className="anchor hidden-xs" href="#Creating-a-String" title="Creating-a-String"><span className="octicon octicon-link" /></a>Creating a String</h2><p>Strings can be used freely or assigned to variables, and can include any character.</p><iframe height={450} src="https://repl.it/@ta_web_mad/Strings1Example?lite=true" allowFullScreen="true" style={{width: '100%'}}>
          </iframe><h2 id="String-Tips-amp-Tricks"><a className="anchor hidden-xs" href="#String-Tips-amp-Tricks" title="String-Tips-amp-Tricks"><span className="octicon octicon-link" /></a>String Tips &amp; Tricks</h2><p>Manipulating and modifying strings in code are common operations. Simple things such as capitalizing a name, or checking to see if a word starts with “T” are commonplace. Let’s look at how to perform some of these simple operations.</p><h3 id="Concatenation"><a className="anchor hidden-xs" href="#Concatenation" title="Concatenation"><span className="octicon octicon-link" /></a>Concatenation</h3><p>You can easily <code>concatenate</code> or add characters to strings with the <code>+</code> or <code>+=</code> operator.</p><iframe height={450} src="https://repl.it/@ta_web_mad/Strings2Example?lite=true" allowFullScreen="true" style={{width: '100%'}}>
          </iframe><h4 id="Numbers-concatenation"><a className="anchor hidden-xs" href="#Numbers-concatenation" title="Numbers-concatenation"><span className="octicon octicon-link" /></a>Numbers concatenation</h4><p>In JavaScript, you can concatenate numbers with strings to add them to a new string:</p><iframe height={300} src="https://repl.it/@ta_web_mad/Strings3Example?lite=true" allowFullScreen="true" style={{width: '100%'}}>
          </iframe><h2 id="String-characters"><a className="anchor hidden-xs" href="#String-characters" title="String-characters"><span className="octicon octicon-link" /></a>String characters</h2><h3 id="Accessing-Characters"><a className="anchor hidden-xs" href="#Accessing-Characters" title="Accessing-Characters"><span className="octicon octicon-link" /></a>Accessing Characters</h3><p>You can access characters inside of strings with their <code>index</code> number. The index determines the character order in the word, from left to right.</p><p>If you introduce a position or index that does not exist or negative, returns <code>undefined</code>.</p><div className="alert alert-warning">
            <p><img alt=":warning:" className="emoji" src="https://cdnjs.cloudflare.com/ajax/libs/emojify.js/1.1.0/images/basic/warning.png" title=":warning:" /> <strong>Be aware, the <a href="https://en.wikipedia.org/wiki/Zero-based_numbering" target="_blank">index starts at 0</a></strong>.</p>
          </div><iframe height={350} src="https://repl.it/@ta_web_mad/Strings4Example?lite=true" allowFullScreen="true" style={{width: '100%'}}>
          </iframe><h3 id="Finding-Characters--Words"><a className="anchor hidden-xs" href="#Finding-Characters--Words" title="Finding-Characters--Words"><span className="octicon octicon-link" /></a>Finding Characters / Words</h3><p>JavaScript has a cool <code>indexOf</code> function that will return the index of a particular character / string occurance.</p><p>If a word has a character two or more times, the <code>indexOf</code> function will return the index of the first occurance.</p><p>If a word does not have that character / string, returns <code>-1</code>.</p><iframe height={450} src="https://repl.it/@ta_web_mad/Strings5Example?lite=true" allowFullScreen="true" style={{width: '100%'}}>
          </iframe><h3 id="Includes"><a className="anchor hidden-xs" href="#Includes" title="Includes"><span className="octicon octicon-link" /></a>Includes</h3><p>Includes is a case sensitive search to see if a particular pattern exists inside of a string.</p><p>If a word does includes character / string, returns <code>true</code>.</p><p>If a word does not include character / string, returns <code>false</code>.</p><iframe height={450} src="https://repl.it/@ta_web_mad/Strings6Example?lite=true" allowFullScreen="true" style={{width: '100%'}}>
          </iframe><h2 id="Summary"><a className="anchor hidden-xs" href="#Summary" title="Summary"><span className="octicon octicon-link" /></a>Summary</h2><p>In this lesson, you have learned how to create and manipulate strings, as well as a few extra tricks that are guaranteed to come in handy in the future.</p><h2 id="Extra-Resources"><a className="anchor hidden-xs" href="#Extra-Resources" title="Extra-Resources"><span className="octicon octicon-link" /></a>Extra Resources</h2><ul>
            <li>Most of the JavaScript String methods can be found at <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String" target="_blank">MDN</a></li>
          </ul></div>
        <div className="ui-toc dropup unselectable hidden-print" style={{display: 'none'}}>
          <div className="pull-right dropdown">
            <a id="tocLabel" className="ui-toc-label btn btn-default" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" title="Table of content">
              <i className="fa fa-bars" />
            </a>
            <ul id="ui-toc" className="ui-toc-dropdown dropdown-menu" aria-labelledby="tocLabel">
              <div className="toc"><ul className="nav"><li className><a href="#Basic-Data-Types-Strings" title="Basic Data Types: Strings">Basic Data Types: Strings</a><ul className="nav"><li><a href="#Learning-Goals" title="Learning Goals">Learning Goals</a></li><li><a href="#What-is-a-string" title="What is a string?">What is a string?</a></li><li><a href="#Creating-a-String" title="Creating a String">Creating a String</a></li><li><a href="#String-Tips-amp-Tricks" title="String Tips & Tricks">String Tips &amp; Tricks</a><ul className="nav"><li><a href="#Concatenation" title="Concatenation">Concatenation</a></li></ul></li><li className><a href="#String-characters" title="String characters">String characters</a><ul className="nav"><li><a href="#Accessing-Characters" title="Accessing Characters">Accessing Characters</a></li><li><a href="#Finding-Characters--Words" title="Finding Characters / Words">Finding Characters / Words</a></li><li className><a href="#Includes" title="Includes">Includes</a></li></ul></li><li><a href="#Summary" title="Summary">Summary</a></li><li className><a href="#Extra-Resources" title="Extra Resources">Extra Resources</a></li></ul></li></ul></div><div className="toc-menu"><a className="expand-toggle" href="#">Expand all</a><a className="back-to-top" href="#">Back to top</a><a className="go-to-bottom" href="#">Go to bottom</a></div>
            </ul>
          </div>
        </div>
        <div id="ui-toc-affix" className="ui-affix-toc ui-toc-dropdown unselectable hidden-print" data-spy="affix" style={{top: 17, display: 'none'}}>
          <div className="toc"><ul className="nav"><li className><a href="#Basic-Data-Types-Strings" title="Basic Data Types: Strings">Basic Data Types: Strings</a><ul className="nav"><li><a href="#Learning-Goals" title="Learning Goals">Learning Goals</a></li><li><a href="#What-is-a-string" title="What is a string?">What is a string?</a></li><li><a href="#Creating-a-String" title="Creating a String">Creating a String</a></li><li><a href="#String-Tips-amp-Tricks" title="String Tips & Tricks">String Tips &amp; Tricks</a><ul className="nav"><li><a href="#Concatenation" title="Concatenation">Concatenation</a></li></ul></li><li className><a href="#String-characters" title="String characters">String characters</a><ul className="nav"><li><a href="#Accessing-Characters" title="Accessing Characters">Accessing Characters</a></li><li><a href="#Finding-Characters--Words" title="Finding Characters / Words">Finding Characters / Words</a></li><li className><a href="#Includes" title="Includes">Includes</a></li></ul></li><li><a href="#Summary" title="Summary">Summary</a></li><li className><a href="#Extra-Resources" title="Extra Resources">Extra Resources</a></li></ul></li></ul></div><div className="toc-menu"><a className="expand-toggle" href="#">Expand all</a><a className="back-to-top" href="#">Back to top</a><a className="go-to-bottom" href="#">Go to bottom</a></div>
        </div>
      </div>
  )
}